# Generated by Django 3.1 on 2020-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotName', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=50)),
            ],
        ),
    ]
