# Generated by Django 3.1 on 2020-08-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songText',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
